### ISSUE TITLE
Support webpack compiler in a nx workspace

### ISSUE THREAD

**Issue by MerlinMoos** [KevinEdry/nestjs-trpc#34]
I am currently working with a Nx workspace using the nestjs-trpc package and encountered an issue when trying to build my NestJS application with Webpack. The following error is triggered during the build process:

```
Error: Could not access root module file.
    at TRPCGenerator.buildRootImportsMap (/home/..../projects/playground/node_modules/nestjs-trpc/dist/generators/trpc.generator.js:92:19)
    at TRPCGenerator.onModuleInit (/home/..../projects/playground/node_modules/nestjs-trpc/dist/generators/trpc.generator.js:26:42)
    at MapIterator.iteratee (/home/..../projects/playground/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
    at MapIterator.next (/home/...../projects/playground/node_modules/iterare/src/map.ts:9:39)
    at IteratorWithOperators.next (/home/..../projects/playground/node_modules/iterare/src/iterate.ts:19:28)
    at Function.from (<anonymous>)
```

This error appears to be related to how the TRPCGenerator is handling imports when using Webpack in a Nx workspace environment. It seems that the TRPCGenerator is not able to correctly resolve the root module file in this context.

**Comment by hrmcdonald** [comment]
Seem to be running into this as well trying to build a docker image to run a built app. We're just using the Nest CLI's SWC builder setup though.

**Comment by hrmcdonald** [comment]
I looked a bit closer and updated the log for this error to include the path its failing to load. In my case that happens to be `./app/apps/src/app/app.module.ts`. However the source map entry for that ts file is in the build output is "../../src/app/app.module.ts". Could these errors be a pathing issue with build output somehow @KevinEdry ?

**Comment by KevinEdry** [comment]
> fails with this error when copied into a container.
You should disable the schema generation when you deploy your server.
If you won't do that, the adapter will try to generate the schema from non-existing ts files when you copy the dist to a container.

**Comment by KevinEdry** [comment]
> I looked a bit closer and updated the log for this error to include the path its failing to load. In my case that happens to be `/app/apps/src/app/app.module.ts`. However the source map entry for that ts file in the build output is `"../../src/app/app.module.ts"`. Could these errors be a pathing issue with build output somehow @KevinEdry ?
> 
> UPDATE: it feels like it has to be some kind of strange issue with pathing? perhaps mine is different than merlins though. If I run the build locally in the `dist` folder it starts as intended. Only fails with this error when copied into a container.

You should disable the schema generation when you deploy your server.
If you won't do that, the adapter will try to generate the schema from non-existing ts files when you copy the dist to a container.

**Comment by hrmcdonald** [comment]
> > I looked a bit closer and updated the log for this error to include the path its failing to load. In my case that happens to be `/app/apps/src/app/app.module.ts`. However the source map entry for that ts file in the build output is `"../../src/app/app.module.ts"`. Could these errors be a pathing issue with build output somehow @KevinEdry ?
> > UPDATE: it feels like it has to be some kind of strange issue with pathing? perhaps mine is different than merlins though. If I run the build locally in the `dist` folder it starts as intended. Only fails with this error when copied into a container.
> 
> You should disable the schema generation when you deploy your server. If you won't do that, the adapter will try to generate the schema from non-existing ts files when you copy the dist to a container.

Aaaah, I see. Well @MerlinMoos I would suspect this is your issue as well.

**Comment by hrmcdonald** [comment]
Confirmed up and running now, thanks @KevinEdry!

**Comment by orecus** [comment]
Ran into this issue today when setting up a basic NX workspace and testing this out. I tried setting up a custom target for NX that runs `nest start --watch`, this causes the same problem as the NX generated commands.

Any assistance would be appreciated in finding a fix for this, perhaps an additional configuration option could be useful to supply the correct paths together with `autoSchemaFile`?

**Comment by KevinEdry** [comment]
> Ran into this issue today when setting up a basic NX workspace and testing this out. I tried setting up a custom target for NX that runs `nest start --watch`, this causes the same problem as the NX generated commands.
> 
> Any assistance would be appreciated in finding a fix for this, perhaps an additional configuration option could be useful to supply the correct paths together with `autoSchemaFile`?

It's all about those map files, can you check the map file and see if it points to the correct path of the TS file?

**Comment by temarusanov** [comment]
+1

**Comment by temarusanov** [comment]
![image](https://github.com/user-attachments/assets/da562415-29bb-4d84-a20f-b20ade8b6689)

`addSourceFileAtPathIfExists()` return this: `/path/to/myproject/dist/packages/server/webpack:/server/external commonjs "@nestjs/common"`

if it helps somehow

**Comment by tony-mack-dealstack** [comment]
I also seem to not be able to get it working with our mono repo using nx
`Error: Could not access root module file.
    at TRPCGenerator.buildRootImportsMap (XXX/node_modules/.pnpm/nestjs-trpc@1.6.1_@nestjs+common@10.3.9_class-transformer@0.5.1_class-validator@0.14.1_reflec_4ds5wpse4ekadcmx6uff63alza/node_modules/nestjs-trpc/lib/generators/trpc.generator.ts:197:13)`
    I tried multiple `autoSchemaFile` paths and didn't get any luck

**Comment by moshequ** [comment]
@temarusanov That's working but after your suggested change I can't import from a shared lib any more

Compiling TypeScript files for project "api"...
apps/api/src/main.ts:9:21 - error TS6059: File '/myapp/libs/shared-lib/index.ts' is not under 'rootDir' '/myapp/apps/api'. 'rootDir' is expected to contain all source files.

import { myValue } from '@myapp/shared-lib';

**Comment by KevinEdry** [comment]
This issue has been resolved by the migration from the TypeScript generator to the standalone Rust CLI.

The old TypeScript generator used `ts-morph` at runtime to parse source files and build import maps (`buildRootImportsMap`). In Nx workspaces with Webpack, the original `.ts` source files weren't accessible to `ts-morph` after bundling, causing the `Could not access root module file` error.

**How the Rust CLI resolves this:**

1. **`ts-morph` completely removed** — the Rust CLI uses SWC to parse TypeScript directly
2. **Operates on source files before bundling** — reads raw `.ts` files from disk, completely decoupled from the build tool
3. **Runs as a standalone CLI** (`npx nestjs-trpc generate`), not at runtime inside the NestJS process
4. **Simple glob-based file discovery** — no dependency on compiler-aware resolution

This makes schema generation fully agnostic to Webpack, Vite, Nx, or any other build tool.
