### ISSUE TITLE
Improve Resilience of FileScanner's Source Map Resolution in nestjs-trpc

### ISSUE THREAD

**Issue by HermannHH** [KevinEdry/nestjs-trpc#47]
The current implementation of FileScanner in the `nestjs-trpc` package encounters issues when it attempts to resolve source maps, especially in scenarios involving E2E testing where TypeScript files are executed directly by Jest. This results in a critical error if the `//# sourceMappingURL` comment is not found in the source file, causing tests to fail unnecessarily.

### Problem

**1. Source Map Resolution Failures:**

- When Jest is used to run tests directly against TypeScript files (.ts), the expected //# sourceMappingURL directive is not present.
- The getSourceMapFromJSPath() method of FileScanner relies on this directive to locate the corresponding source map file.
- This results in an error that interrupts testing since it cannot locate the .map file to properly trace back to the TypeScript source.

**2. Warning Noise in Test Environment:**

- The original implementation throws an error and logs a warning when the source map cannot be resolved.
- During testing, this leads to a lot of unnecessary noise, as Jest runs without the same .js file artifacts that would be present in a production environment.

**Proposed Solution:** The proposed changes address these problems in the following ways:

**1. Fallback to Default Path Resolution:**

- When FileScanner fails to resolve the source map, it now falls back gracefully to use the .js file path directly instead of throwing an error. This ensures that testing continues even if the source map is missing.

**2. Suppress Warnings During Test Runs:**

- The new implementation adds logic to suppress warnings when the NODE_ENV is set to 'test'. This prevents unnecessary warning messages from cluttering the test output, improving the developer experience when running tests.

### Changes Made:

1. Wrapped the source map resolution logic inside a try-catch block to handle failures more gracefully.
2. Added an environment-based check (process.env.NODE_ENV !== 'test') to conditionally suppress warnings during test runs.
3. Improved error messages to provide more informative context in case file reading or source map parsing fails.

### Impact:

1. Improved Developer Experience: Reduces noise during testing, allowing developers to focus on meaningful test output rather than warnings about missing source maps.
2. Resilience: The fallback mechanism ensures that the absence of a source map does not break the test or development workflow.

### Reproduction Steps:

1. Run E2E tests in a project that uses nestjs-trpc and TypeScript.
2. The tests will fail with an error similar to:
`Could not find source file for path /path/to/file.ts, make sure "sourceMap" is enabled in your tsconfig.`
3. This happens because Jest directly runs against TypeScript files, which do not contain inline source map comments.

**Proposed Solution (Code Example):**

```
public getCallerFilePath(skip: number = 2): string {
  const originalPrepareStackTrace = Error.prepareStackTrace;
  Error.prepareStackTrace = (_, stack) => stack;
  const error = new Error();
  const stack = error.stack as unknown as NodeJS.CallSite[];
  Error.prepareStackTrace = originalPrepareStackTrace;

  const caller = stack[skip];
  const jsFilePath = caller?.getFileName();

  if (jsFilePath == null) {
    throw new Error(`Could not find caller file: ${caller}`);
  }

  try {
    // Attempt to find the source map file and extract the original TypeScript path
    const sourceMap = this.getSourceMapFromJSPath(jsFilePath);
    return this.normalizePath(path.resolve(jsFilePath, '..', sourceMap.sources[0]));
  } catch (error) {
    // Suppress the warning if in test environment
    if (process.env.NODE_ENV !== 'test') {
      console.warn(`Warning: Could not resolve source map for ${jsFilePath}. Falling back to default path resolution.`);
    }
    return this.normalizePath(jsFilePath);
  }
}
```

### Expected Benefits:

- This change will enhance resilience when resolving source maps, especially during testing.
- Developers running tests will experience less clutter in the test logs, making it easier to focus on meaningful output.

### Related Code:

- File: `file.scanner.ts`
- Relevant Methods: `getCallerFilePath()`, `getSourceMapFromJSPath()`

**Additional Context:** This improvement is particularly beneficial for developers running integration or E2E tests using tools like Jest. Since Jest runs directly with TypeScript files without the full compilation process (including .map generation), falling back gracefully when source maps are missing provides a much more robust experience.

**Comment by HermannHH** [comment]
Here is a [sample repo](https://github.com/HermannHH/nest-demo) that illustrates the error being fixed by the PR. The error can be recreated by simply running the `pnpm test:e2e` command from the repo root.

The error looks like this:

```
pnpm test:e2e 

 FAIL  test/app.e2e-spec.ts
  ● Test suite failed to run

    Could not find source file for path /nest-demo/src/ping/ping.router.ts, make sure "sourceMap" is enabled in your tsconfig.

      1 | import { Query, Router } from 'nestjs-trpc';
      2 |
    > 3 | @Router({ alias: 'ping' })
        |        ^
      4 | export class PingRouter {
      5 |   constructor() {}
      6 |

      at FileScanner.getSourceMapFromJSPath (../node_modules/.pnpm/nestjs-trpc@1.6.1_@nestjs+common@10.4.12_reflect-metadata@0.2.2_rxjs@7.8.1__@nestjs+core@10.4_zrzpprwbst6k2iq6e5ldm5erom/node_modules/nestjs-trpc/lib/scanners/file.scanner.ts:55:13)
...

Test Suites: 1 failed, 1 total
```

I have already created a [PR](https://github.com/KevinEdry/nestjs-trpc/pull/46).

**Comment by KevinEdry** [comment]
The library is searching for source maps only when generating a schema, if you disable that during the testing environments, your tests should pass with no issue, have you tried that?

**Comment by mrosnerr** [comment]
I ran into a similar issue where even if `autoSchemaFile` is not enabled, Jest still ran into this error when using the `@nestjs/common` `applyDecorators` utility.

Applying the change from @HermannHH's PR appears to have fixed this entry point into the issue as well.

# Example

```
import { AuthnMiddleware } from '@/common/middlewares/authn.middleware';
import { AuthzMiddleware } from '@/common/middlewares/authz.middleware';
import { ResponseTimeMiddleware } from '@/common/middlewares/responseTime.middleware';
import { applyDecorators } from '@nestjs/common';
import { UseMiddlewares, Router } from 'nestjs-trpc';

export const AuthedRoute = (options: { alias: string }) => {
  return applyDecorators(
    Router({ alias: options.alias }),
    UseMiddlewares(ResponseTimeMiddleware, AuthnMiddleware, AuthzMiddleware),
  );
};
```

## Error
```
 ● Test suite failed to run

    Could not find source file for path src/common/decorators/authedRoute.decorator.ts, make sure "sourceMap" is enabled in your tsconfig.

       9 |
      10 |   return applyDecorators(
    > 11 |     Router({ alias: options.alias }),
         |           ^
      12 |     UseMiddlewares(ResponseTimeMiddleware, AuthnMiddleware, AuthzMiddleware),
      13 |   );
      14 | };

      at FileScanner.getSourceMapFromJSPath (../../node_modules/.pnpm/nestjs-trpc@1.6.1_@nestjs+common@10.4.11_reflect-metadata@0.2.2_rxjs@7.8.1__@nestjs+core@10.4_u2louwtuauukeuddklpdhhhsmq/node_modules/nestjs-trpc/lib/scanners/file.scanner.ts:55:13)
...
```

**Comment by mrosnerr** [comment]
@KevinEdry As a follow up to this, I was looking to kick up a PR to fix failing tests before another change I'd like to propose, and it seems this is affecting the [router.decorator.spec.ts](https://github.com/KevinEdry/nestjs-trpc/blob/c4e45b453c47f526b2b8e094b77feac9a21e42dc/packages/nestjs-trpc/lib/decorators/__tests__/router.decorator.spec.ts) tests within this repo also.

```
~/dev/nestjs-trpc main *1 !6 ❯ yarn test                                                                                                                                                               5s 08:10:07 PM
[nestjs-trpc]: Process started
[nestjs-trpc]: FAIL lib/decorators/__tests__/router.decorator.spec.ts
[nestjs-trpc]:   ● Router Decorator › should set router metadata without alias
[nestjs-trpc]:
[nestjs-trpc]:     Could not find source file for path /Users/teal/dev/nestjs-trpc/packages/nestjs-trpc/lib/decorators/__tests__/router.decorator.spec.ts, make sure "sourceMap" is enabled in your tsconfig.
[nestjs-trpc]:
[nestjs-trpc]:       53 |
[nestjs-trpc]:       54 |     if (exec == null) {
[nestjs-trpc]:     > 55 |       throw new Error(
[nestjs-trpc]:          |             ^
[nestjs-trpc]:       56 |         `Could not find source file for path ${sourcePath}, make sure "sourceMap" is enabled in your tsconfig.`,
[nestjs-trpc]:       57 |       );
[nestjs-trpc]:       58 |     }
[nestjs-trpc]:
[nestjs-trpc]:       at FileScanner.getSourceMapFromJSPath (lib/scanners/file.scanner.ts:55:13)
[nestjs-trpc]:       at FileScanner.getSourceMapFromJSPath [as getCallerFilePath] (lib/scanners/file.scanner.ts:28:28)
[nestjs-trpc]:       at getCallerFilePath (lib/decorators/router.decorator.ts:24:28)
[nestjs-trpc]:       at Object.<anonymous> (lib/decorators/__tests__/router.decorator.spec.ts:7:12)
```

**Comment by KevinEdry** [comment]
Tests are inherently complex for these kind of libraries, I have an open task to fix them, but we are changing things so quickly thats its a challenge to keep up, try and proceed with failing tests, i'lll fix the tests when you open a PR.

**Comment by KevinEdry** [comment]
@HermannHH I've merged your changes, going to create a new version shortly
